### ISSUE TITLE
Stage hunks is not listed in the actions

### ISSUE THREAD

**Issue by marcbelmont** [torgeir/helm-hunks.el#2]
The documentation says C-s can be used to stage a hunk. When you're in the helm-hunks buffer, shouldn't the actions (when you press TAB) list stage hunk?

Thanks for this great mode.

**Comment by torgeir** [comment]
That's because the stage hunks functionality is not an "action" in terms of helm, but rather [a keybinding in the helm-map, available only when helm-hunks is active](https://github.com/torgeir/helm-hunks.el/blob/master/helm-hunks.el#L323-L333).

`C-s` should still work, though, when your _selection is on a hunk in the helm-hunks buffer_.

> Thanks for this great mode.

Your welcome! Glad you like it

**Comment by marcbelmont** [comment]
Ok, thanks for the clarification.
